version: "3"
services:
  vespa:
    image: vespaengine/vespa
    container_name: vespa-amazon-product-search
    ports:
      - 8080:8080
      - 19071:19071
    volumes:
      - vespa-data:/opt/vespa/var
volumes:
  vespa-data:
    driver: local
