<?xml version="1.0" encoding="UTF-8" ?>
<services version="1.0" xmlns:deploy="vespa">
    <container id="container" version="1.0">
        <document-api />
        <document-processing />
        <search />
    </container>
    <content id="product" version="1.0">
        <redundancy>1</redundancy>
        <documents>
            <document type="product" mode="index" />
            <document-processing cluster="container" />
        </documents>
        <nodes>
            <node hostalias="node1" distribution-key="0" />
        </nodes>
    </content>
</services>
