version: "3"
services:
  es-8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: es-8
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/8/data

  kibana-8:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana-8
    ports:
      - 5602:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es-8:9200
volumes:
  es-data:
    driver: local
