version: "3"
services:
  es-8:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.4
    container_name: amazon-product-search-es8
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/8/data
    profiles:
      - elasticsearch
  kibana-8:
    depends_on:
      - es-8
    image: docker.elastic.co/kibana/kibana:8.10.4
    container_name: amazon-product-search-kibana8
    ports:
      - 5602:5601
    environment:
      - ELASTICSEARCH_HOSTS=http://es-8:9200
    profiles:
      - elasticsearch

  vespa:
    image: vespaengine/vespa
    container_name: amazon-product-search-vespa
    ports:
      - 8080:8080
      - 19071:19071
    volumes:
      - vespa-data:/opt/vespa/var
    profiles:
      - vespa

volumes:
  es-data:
    driver: local
  vespa-data:
    driver: local
