[tool.poetry]
name = "amazon-product-search"
version = "0.1.0"
description = ""
authors = ["rejasupotaro"]

[tool.poetry.dependencies]
python = "3.10.8"
streamlit = "^1.13.0"
pandas = "^1.5.0"
apache-beam = {version = "2.43.0", extras = ["gcp"]}
fugashi = {extras = ["unidic"], version = "^1.2.0"}
ipadic = "^1.0.0"
elasticsearch = "8.4.3"
plotly = "^5.10.0"
tqdm = "^4.64.1"
torch = "1.12.1"
transformers = "^4.23.1"
sentence-transformers = "^2.2.2"
watchdog = "^2.1.9"
streamlit-aggrid = "^0.3.3"
pke = {git = "https://github.com/boudinfl/pke.git", rev = "2.0.0"}
keybert = "^0.7.0"
more-itertools = "^9.0.0"
scikit-learn = "^1.2.0"

[tool.poetry.dev-dependencies]
pytest = "^7.2"
pytest-cov = "^4.0.0"
black = "^22.10.0"
invoke = "^1.7.3"
isort = "^5.10.1"
mypy = "^0.982"
pyproject-flake8 = "^5.0.4"
jupyterlab = "3.5.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.flake8]
max-line-length = 120
ignore = "E203,W503"

[tool.mypy]
python_version = "3.10"
mypy_path = ["src"]
ignore_missing_imports = true
