[tool.poetry]
name = "amazon-product-search"
version = "0.1.0"
description = ""
authors = ["rejasupotaro"]

[tool.poetry.dependencies]
python = "3.10.8"
invoke = "^1.7.3"
streamlit = "1.21.0"
pandas = "^1.5.0"
apache-beam = "2.45.0"
fugashi = {extras = ["unidic"], version = "^1.2.0"}
ipadic = "^1.0.0"
elasticsearch = "8.7.0"
plotly = "^5.10.0"
tqdm = "^4.64.1"
torch = "^2.0.0"
transformers = "^4.25.1"
sentence-transformers = "^2.2.2"
watchdog = "^2.1.9"
streamlit-aggrid = "^0.3.3"
keybert = "^0.7.0"
more-itertools = "^9.0.0"
scikit-learn = "^1.2.0"
tabulate = "^0.9.0"
pytorch-lightning = "^1.9.5"
tensorboard = "^2.11.0"
pyvespa = "0.33.0"
unidic-lite = "^1.0.8"
polars = {version = "^0.16.0", extras = ["numpy", "pandas", "pyarrow"]}
types-requests = "^2.28.11.17"
docker = "^6.0.1"
eland = "8.7.0"
amazon-product-search-dense-retrieval = {git = "https://github.com/rejasupotaro/amazon-product-search-dense-retrieval.git"}

[tool.poetry.group.dev.dependencies]
pytest = "^7.2"
pytest-cov = "^4.0.0"
black = "^22.12.0"
isort = "^5.10.1"
mypy = "^0.982"
pyproject-flake8 = "^5.0.4"
jupyterlab = "3.5.0"
seaborn = "^0.12.1"
ruff = "^0.0.265"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
# For available rules, see https://beta.ruff.rs/docs/rules/
select = ["E", "F", "W", "C90", "I", "N", "B", "C4", "SIM", "RUF", "TID", "TCH", "YTT", "Q", "ISC", "PT"]
line-length = 120

[tool.ruff.isort]
known-first-party = [
    "amazon_product_search",
    "amazon_product_search_dense_retrieval",
    "demo",
]

[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.flake8]
max-line-length = 120
ignore = "E203,W503"

[tool.mypy]
python_version = "3.10"
mypy_path = ["src"]
ignore_missing_imports = true
