[browser]
# Whether to send usage statistics to Streamlit.
# Default: true
gatherUsageStats = false

[theme]
# Primary accent for interactive elements
primaryColor = "#FF9900"
backgroundColor="#FFFFFF"
textColor="#000000"
font = "sans serif"
# font = "serif"
